import { Murecho } from "next/font/google";
import "../styles/globals.scss";
import Header from "../app/components/header/Header";
import Footer from "../app/components/footer/Footer";

const murecho = Murecho({ 
  subsets: ["latin"],
  weights: [400, 700],
  display: "swap",
 });

export const metadata = {
  title: "Cult Crew",
  description: "Generated by create next app",
  // Add favicon and other metadata here
};

export default function RootLayout({ children }) {
  return (
    <html lang="de">
      
      <body className={murecho.className}>
        <Header />
          {children}
        <Footer />
        </body>
      
    </html>
  );
}
